@startuml
|Замовник|

start
:Висуває свої вимоги;
|#Red/Yellow|Менеджер|
:Перевіряє умови замовника;
:Формує новий план створення опитування;
:Передає звіт з результатами проведенного опитування;
|Замовник|

stop
@enduml
