@startuml

    actor "Менеджер" as Manager #Red/Yellow
    actor "Аналітик" as Analyst #Red/Yellow
    actor "Експерт" as Expert #Red/Yellow
    actor "Замовник" as Customer #Red/Yellow
    
    Customer -> Manager : Дає завдання 
    Manager -> Analyst : Передає завдання 
    Analyst -> Analyst :  Перевіряє замовлення\n на можливість реалізації.\n Cтворює опитування.
    Analyst -> Manager : Передає створене\n опитування
    Manager -> Expert : Запрошує на проходження\n опитування
    Expert -> Manager : Передає результати проходження\n опитування
    Manager -> Analyst : Передає результати проходження\n опитування
    Analyst -> Analyst : Проводить аналіз\n відповідей\n Створює звіт 
    Analyst -> Manager : Передає звіт по результатам\n опитування
    Manager -> Customer : Передає звіт з результатами.
    
@enduml
